-- ============================================================================
-- 05: Raw → Silver (Handled by Airflow — no DDL here)
-- ============================================================================
--
-- Pipeline flow:
--   01 Kafka engine tables   → consume topics
--   02 Raw tables            → append-only JSON storage
--   03 Ingestion MVs         → Kafka engine → raw tables (pass-through)
--   04 Silver tables         → CollapsingMergeTree (parsed, typed columns)
--   ** Airflow DAG **        → reads raw, parses JSON, adds sign, inserts into 04
--   06 Mart views            → GROUP BY key HAVING sum(sign) > 0
--
-- This layer (raw → silver) is handled entirely by the Airflow DAG:
--   airflow/dags/property_tax_raw_to_silver.py
--
-- The DAG runs daily at 01:30 AM and:
--   1. Fetches raw events by lastModifiedTime window
--   2. Parses JSON, flattens arrays (units, owners), pivots demand details
--   3. Detects INSERT vs UPDATE (createdTime == lastModifiedTime)
--   4. Inserts sort-key-only cancel row (sign=-1) for UPDATEs
--   5. Inserts full new row (sign=+1) for both INSERTs and UPDATEs
--
-- No tables or MVs are created in this file.
-- ============================================================================
